homepage:
    path:     /
    defaults: { _controller:GTBundle:Home:index }

# LISTADOS #
list_persona:
    path:   /persona
    defaults: { _controller:GTBundle:Persona:list}    
list_perfil:
    path:   /perfil
    defaults: { _controller:GTBundle:Perfil:list}  
list_empresa:
    path:   /empresa
    defaults: { _controller:GTBundle:Empresa:list}
list_ucl:
    path:   /ucl
    defaults: { _controller:GTBundle:Ucl:list}
list_competencia:
    path:   /competenciaConductual
    defaults: { _controller:GTBundle:CompetenciaConductual:list}
list_curso:
    path:   /curso
    defaults: { _controller:GTBundle:Curso:list}     
list_evaluacion:
    path:   /evaluacion
    defaults: { _controller:GTBundle:Evaluacion:list}     
# FIN DE LISTADOS #

# METODOS POST #
perfil_add:
    path:   /perfil/add
    defaults: { _controller:GTBundle:Perfil:add}
    options:
        expose: true
persona_add:
    path:   /persona/add
    defaults: { _controller:GTBundle:Persona:add}
    options:
        expose: true
empresa_add:
    path:   /empresa/add
    defaults: { _controller:GTBundle:Empresa:add}
    options:
        expose: true
ucl_add:
    path:   /ucl/add
    defaults: { _controller:GTBundle:Ucl:add}
    options:
        expose: true
competencia_add:
    path:   /competenciaConductual/add
    defaults: { _controller:GTBundle:CompetenciaConductual:add}
    options:
        expose: true
curso_add:
    path:   /curso/add
    defaults: { _controller:GTBundle:Curso:add}
    options:
        expose: true
evaluacion_add:
    path:   /evaluacion/add
    defaults: { _controller:GTBundle:Evaluacion:add}
    options:
        expose: true
# FIN METODOS POST #

# METODOS DELETE #
perfil_delete:
    path:   /perfil/delete/{id}
    defaults: { _controller:GTBundle:Perfil:delete}
persona_delete:
    path:   /persona/delete/{id}
    defaults: { _controller:GTBundle:Persona:delete}
empresa_delete:
    path:   /empresa/delete/{id}
    defaults: { _controller:GTBundle:Empresa:delete}
competencia_delete:
    path:   /competenciaConductual/delete/{id}
    defaults: { _controller:GTBundle:CompetenciaConductual:delete}
ucl_delete:
    path:   /ucl/delete/{id}
    defaults: { _controller:GTBundle:Perfil:delete}
curso_delete:
    path:   /curso/delete/{id}
    defaults: { _controller:GTBundle:Perfil:delete}
# FIN METODOS DELETE #