homepage:
    path:     /
    defaults: { _controller:GTBundle:Home:index }

# LISTADOS #
persona_list:
    path:   /persona
    defaults: { _controller:GTBundle:Persona:list}    
perfil_list:
    path:   /perfil
    defaults: { _controller:GTBundle:Perfil:list}  
empresa_list:
    path:   /empresa
    defaults: { _controller:GTBundle:Empresa:list}
ucl_list:
    path:   /ucl
    defaults: { _controller:GTBundle:Ucl:list}
conducta_list:
    path:   /conducta
    defaults: { _controller:GTBundle:Conducta:list}
curso_list:
    path:   /curso
    defaults: { _controller:GTBundle:Curso:list}     
evaluacion_list:
    path:   /evaluacion
    defaults: { _controller:GTBundle:Evaluacion:list}     
# FIN DE LISTADOS #

# METODOS POST #
perfil_add:
    path:   /perfil/add
    defaults: { _controller:GTBundle:Perfil:add}
    options:
        expose: true
persona_add:
    path:   /persona/add
    defaults: { _controller:GTBundle:Persona:add}
    options:
        expose: true
empresa_add:
    path:   /empresa/add
    defaults: { _controller:GTBundle:Empresa:add}
    options:
        expose: true
ucl_add:
    path:   /ucl/add
    defaults: { _controller:GTBundle:Ucl:add}
    options:
        expose: true
conducta_add:
    path:   /conducta/add
    defaults: { _controller:GTBundle:Conducta:add}
    options:
        expose: true
curso_add:
    path:   /curso/add
    defaults: { _controller:GTBundle:Curso:add}
    options:
        expose: true
evaluacion_add:
    path:   /evaluacion/add
    defaults: { _controller:GTBundle:Evaluacion:add}
    options:
        expose: true
# FIN METODOS POST #

# METODOS PUT #
perfil_update:
    path:   /perfil/update/{id}
    defaults: { _controller:GTBundle:Perfil:update}
    options:
        expose: true
perfil_edit:
    path:   /perfil/edit/{id}
    defaults: { _controller:GTBundle:Perfil:edit}
    options:
        expose: true
persona_update:
    path:   /persona/update/{id}
    defaults: { _controller:GTBundle:Persona:update}
    options:
        expose: true
empresa_update:
    path:   /empresa/update/{id}
    defaults: { _controller:GTBundle:Empresa:update}
    options:
        expose: true
ucl_update:
    path:   /ucl/update/{id}
    defaults: { _controller:GTBundle:Ucl:update}
    options:
        expose: true
conducta_update:
    path:   /conducta/update/{id}
    defaults: { _controller:GTBundle:Conducta:update}
    options:
        expose: true
curso_update:
    path:   /curso/update/{id}
    defaults: { _controller:GTBundle:Curso:update}
    options:
        expose: true
evaluacion_update:
    path:   /evaluacion/update/{id}
    defaults: { _controller:GTBundle:Evaluacion:update}
    options:
        expose: true
# FIN METODOS POST #


# METODOS DELETE #
perfil_delete:
    path:   /perfil/delete/{id}
    defaults: { _controller:GTBundle:Perfil:delete}
persona_delete:
    path:   /persona/delete/{id}
    defaults: { _controller:GTBundle:Persona:delete}
empresa_delete:
    path:   /empresa/delete/{id}
    defaults: { _controller:GTBundle:Empresa:delete}
conducta_delete:
    path:   /conducta/delete/{id}
    defaults: { _controller:GTBundle:Conducta:delete}
ucl_delete:
    path:   /ucl/delete/{id}
    defaults: { _controller:GTBundle:Ucl:delete}
curso_delete:
    path:   /curso/delete/{id}
    defaults: { _controller:GTBundle:Curso:delete}
evaluacion_delete:
    path:   /evaluacion/delete/{id}
    defaults: { _controller:GTBundle:Evaluacion:delete}
# FIN METODOS DELETE #