<?php

namespace GTBundle\Repository;

/**
 * ActividadClaveCriterioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadClaveCriterioRepository extends \Doctrine\ORM\EntityRepository
{
}
