<?php

namespace GTBundle\Repository;

/**
 * ActividadClaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadClaveRepository extends \Doctrine\ORM\EntityRepository
{
}
