<?php

namespace GTBundle\Repository;

/**
 * CompetenciaConductualIndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenciaConductualIndicadorRepository extends \Doctrine\ORM\EntityRepository
{
}
