<?php

namespace GTBundle\Repository;

/**
 * ConductaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConductaRepository extends \Doctrine\ORM\EntityRepository
{
}
