<?php

namespace GTBundle\Repository;

/**
 * CursoModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoModuloRepository extends \Doctrine\ORM\EntityRepository
{
}
