<?php

namespace GTBundle\Repository;

/**
 * CursoIndicadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoIndicadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
