<?php

namespace GTBundle\Repository;

/**
 * CursoActividadClaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoActividadClaveRepository extends \Doctrine\ORM\EntityRepository
{
}
