<?php

namespace GTBundle\Repository;

/**
 * PerfilUclRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilUclRepository extends \Doctrine\ORM\EntityRepository
{
}
