<?php

namespace GTBundle\Repository;

/**
 * UclActividadClaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UclActividadClaveRepository extends \Doctrine\ORM\EntityRepository
{
}
